# Generated by Django 4.1.3 on 2022-12-13 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
